export const drivers = [
    { value: 23, label: "Alexander Albon" },
    { value: 14, label: "Fernando Alonso" },
    { value: 12, label: "Kimi Antonelli" },
    { value: 87, label: "Oliver Bearman" },
    { value: 5,  label: "Gabriel Bortoleto" },
    { value: 43, label: "Franco Colapinto" },
    { value: 10, label: "Pierre Gasly" },
    { value: 6,  label: "Isack Hadjar" },
    { value: 44, label: "Lewis Hamilton" },
    { value: 27, label: "Nico Hulkenberg" },
    { value: 30, label: "Liam Lawson" },
    { value: 16, label: "Charles Leclerc" },
    { value: 4,  label: "Lando Norris" },
    { value: 31, label: "Esteban Ocon" },
    { value: 81, label: "Oscar Piastri" },
    { value: 63, label: "George Russell" },
    { value: 55, label: "Carlos Sainz" },
    { value: 18, label: "Lance Stroll" },
    { value: 22, label: "Yuki Tsunoda" },
    { value: 1, label: "Max Verstappen" },
    { value: 61, label: "Jack Doohan" },
  ];